version: '3'
services:
  dev-env:
    container_name: deep-learning-dev
    build: ./
    volumes:
      - ./:/local
    stdin_open: true
    tty: true

  juoyter-notebook-local:
    image: jupyter/datascience-notebook
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.password='' --NotebookApp.token=''"


